const english: Record<string, string> = {
  "定义目标": "Define the goal", "先写清模型要完成的任务，以及怎样才算成功。": "Describe what the model should do and what success looks like.",
  "连接算力": "Connect compute", "用一次性命令连接普通 Ubuntu 电脑、Linux NVIDIA GPU 或 Apple Silicon Mac。": "Use one command to connect an Ubuntu computer, Linux NVIDIA GPU, or Apple Silicon Mac.",
  "准备数据": "Prepare data", "在你的环境中检查格式、重复、长度、切分与泄漏风险。": "Check formats, duplicates, length, splits, and leakage risks in your environment.",
  "设置训练": "Configure training", "选择模型与速度、质量偏好，系统给出可执行方案。": "Choose a model and your speed–quality preference, then get an executable plan.",
  "比较结果": "Compare results", "用同一测试集比较基础模型、checkpoint 与微调模型。": "Compare the base model, checkpoints, and fine-tuned model on the same test set.",
  "取得模型": "Get the model", "把 Adapter、合并权重、Hugging Face 或 GGUF 留在自己的存储中。": "Keep the adapter, merged weights, Hugging Face model, or GGUF in your own storage.",
  "LLMWEB 会上传我的原始训练数据吗？": "Will LLMWEB upload my raw training data?", "默认不会。数据检查、训练和评测在你连接的电脑上执行；网页只接收统计、进度、指标和你主动授权的少量预览。": "No by default. Data checks, training, and evaluation run on your connected computer; the web app receives only statistics, progress, metrics, and previews you explicitly allow.",
  "我需要准备什么环境？": "What environment do I need?", "第一次练习可使用 4 核 8G、至少 20GB 可用空间的 Ubuntu 普通电脑；进阶微调可使用 Linux NVIDIA GPU 或 Apple Silicon Mac。": "For your first run, use an Ubuntu computer with 4 CPU cores, 8 GB RAM, and at least 20 GB free. For advanced fine-tuning, use a Linux NVIDIA GPU or Apple Silicon Mac.",
  "支持哪些微调方式？": "Which fine-tuning methods are supported?", "支持文本 SFT 与 LoRA；Linux NVIDIA GPU 还支持 4 位 QLoRA。Apple Silicon 使用原生 Metal/MPS LoRA，并提供固定版本的 Qwen2.5 0.5B、1.5B 与 3B 指令模型。": "Text SFT and LoRA are supported; Linux NVIDIA GPUs also support 4-bit QLoRA. Apple Silicon uses native Metal/MPS LoRA. Fixed revisions of Qwen2.5 0.5B, 1.5B, and 3B Instruct are available.",
  "怎样判断微调真的有效？": "How do I know fine-tuning actually worked?", "LLMWEB 会先建立基础模型基线，再用同一测试集复测候选模型；页面同时展示质量变化、推理性能和失败样本，避免只看一条损失曲线。": "LLMWEB establishes a base-model baseline, then retests candidates on the same test set. It shows quality changes, inference performance, and failed samples so you do not rely on a loss curve alone.",
  "LLMWEB 会托管训练后的模型吗？": "Does LLMWEB host trained models?", "默认不会。模型权重、checkpoint 和导出产物保存在你的 GPU 主机或你自己的 S3 兼容存储中，平台只保留版本、指标和产物引用。": "No by default. Weights, checkpoints, and exports stay on your compute host or S3-compatible storage; the platform keeps only versions, metrics, and artifact references.",
  "工作流程": "Workflow", "数据边界": "Data boundaries", "方案": "Plans", "常见问题": "FAQ", "进入工作台": "Open workbench",
  "从普通电脑入门的模型训练工作台": "A model-training workbench that starts on an ordinary computer", "把一次模型微调，": "Turn model fine-tuning", "变成一条清晰的网页流程。": "into a clear web workflow.",
  "先用一台 4 核 8G Ubuntu 电脑完成第一次模型训练；有 GPU 时，再继续进行 SFT / LoRA / QLoRA 微调。数据检查、训练前后评测和模型导出都在同一条网页流程中完成。": "Complete your first model training run on an Ubuntu computer with 4 CPU cores and 8 GB RAM. Add a GPU later for SFT, LoRA, or QLoRA. Data checks, before-and-after evaluation, and model export all happen in one web workflow.",
  "开始建立训练项目": "Create a training project", "查看完整流程": "View the full workflow", "入门：Ubuntu 4 核 8G · 进阶：Linux NVIDIA GPU 或 Apple Silicon": "Start: Ubuntu, 4 cores / 8 GB · Advanced: Linux NVIDIA GPU or Apple Silicon",
  "训练中": "Training", "当前阶段": "Current stage", "微调模型": "Fine-tune model", "数据版本与基础模型基线已经就绪。": "The data version and base-model baseline are ready.", "进度": "Progress", "验证损失": "Validation loss", "剩余时间": "Time left", "38 分钟": "38 min", "原始数据留在你的环境": "Raw data stays in your environment", "网页只接收统计、进度和授权预览": "The web app receives only statistics, progress, and approved previews",
  "数据不搬家": "Data stays put", "原始数据、权重与 checkpoint 默认留在你的环境": "Raw data, weights, and checkpoints stay in your environment by default", "无需开放端口": "No open ports", "连接程序主动访问网页服务，不需要公网 IP 或 SSH": "The connector reaches the web service outbound; no public IP or SSH is required", "结果可核验": "Verifiable results", "同一测试集对比训练前后，不把“跑完”当“有效”": "Compare before and after on the same test set; completion alone is not proof",
  "从训练配置到可用结果": "From training settings to usable results", "你负责目标与判断，": "You own the goal and judgment;", "LLMWEB 收起训练流程的复杂度。": "LLMWEB handles the workflow complexity.", "不再在命令、配置文件、日志窗口和零散脚本之间来回切换。每一步都围绕用户要完成的动作，并留下下一步可以依赖的结果。": "Stop switching among commands, config files, logs, and scattered scripts. Each step centers on the action you need to complete and leaves a result the next step can rely on.",
  "先让数据可训练": "Make data trainable", "在数据离开你的环境之前就完成格式、重复、Token 长度、切分和泄漏检查，并形成不可变的数据版本。": "Check formats, duplicates, token length, splits, and leakage before data leaves your environment, then create an immutable data version.", "让训练过程看得懂": "Make training understandable", "持续展示阶段、剩余时间、损失、吞吐和 GPU 状态；断开网页不会终止已被主机接受的训练。": "See the stage, time remaining, loss, throughput, and GPU status. Closing the web app does not stop a run accepted by your host.", "用证据选择模型": "Choose with evidence", "把基础模型、候选 checkpoint 和历史模型放在同一测试条件下比较，再结合盲测样本与性能代价作决定。": "Compare the base model, candidate checkpoints, and previous models under identical test conditions, then decide using blind samples and performance cost.",
  "一套连续工作流": "One continuous workflow", "从任务目标，到自己的模型产物。": "From a task goal to your own model artifact.",
  "数据边界从产品设计开始": "Data boundaries start with product design", "训练发生在你的算力上，": "Training runs on your compute,", "不是在我们的黑盒里。": "not inside our black box.", "网页负责组织项目、展示统计和推进动作；连接程序在你的主机上检查数据、运行训练、评测和导出。你不需要把 SSH 权限、存储凭证或原始数据交给平台。": "The web app organizes projects, shows statistics, and advances actions. The connector checks data, trains, evaluates, and exports on your host. You never need to give the platform SSH access, storage credentials, or raw data.",
  "原始训练、验证与测试数据留在用户环境": "Raw training, validation, and test data stays in your environment", "模型权重、checkpoint 与导出产物留在用户主机或自己的 S3": "Weights, checkpoints, and exports stay on your host or your S3", "网页只接收完成工作所需的统计、进度、指标与授权预览": "The web app receives only the statistics, progress, metrics, and approved previews needed to do the work", "查看 LLMWEB 产品法律补充说明 →": "View the LLMWEB product legal supplement →",
  "网页工作台": "Web workbench", "目标 · 状态 · 指标": "Goals · status · metrics", "不保存原始训练数据": "No raw training data stored", "出站连接": "Outbound connection", "你的训练电脑": "Your training computer", "数据 · 训练 · 模型": "Data · training · models", "你控制主机与存储位置": "You control the host and storage",
  "简单透明的方案": "Simple, transparent plans", "算力属于你，订阅只为更顺畅的训练管理。": "Your compute is yours. The subscription makes training management easier.", "两个方案都使用你自己的电脑和存储；LLMWEB 不收取训练时长或算力费用。": "Both plans use your own computer and storage. LLMWEB does not charge for training time or compute.", "开始使用": "Get started", "升级 Pro": "Upgrade to Pro", "个活跃项目": " active projects", "方案暂时无法加载，购买入口已安全关闭；免费工作台不受影响。": "Plans are temporarily unavailable, so purchasing is disabled. The free workbench is unaffected.",
  "适用边界": "Who it is for", "选择 LLMWEB，如果你想掌控算力与数据。": "Choose LLMWEB when you want control of your compute and data.", "适合": "A good fit", "个人开发者与小型 AI 团队": "Independent developers and small AI teams", "想先用普通 Ubuntu 电脑学会完整训练流程": "Learn the complete workflow first on an ordinary Ubuntu computer", "已有 Linux NVIDIA GPU 或 Apple Silicon Mac": "Already have a Linux NVIDIA GPU or Apple Silicon Mac", "希望减少训练框架和命令行负担": "Want less framework and command-line overhead", "希望模型产物留在自己的基础设施": "Want model artifacts to stay in your infrastructure", "暂不适合": "Not yet a fit", "需要托管算力或生产推理的平台": "Teams that need hosted compute or production inference", "没有可连接的 Ubuntu、Linux GPU 或 Apple Silicon 电脑": "No connectable Ubuntu, Linux GPU, or Apple Silicon computer", "需要 Windows、AMD、Intel GPU 或多机训练": "Need Windows, AMD/Intel GPUs, or multi-node training", "需要 DPO、PPO、GRPO 或多模态训练": "Need DPO, PPO, GRPO, or multimodal training", "希望平台直接托管生产推理服务": "Want the platform to host production inference",
  "开始前，你可能还想确认这些。": "A few things you may want to confirm before starting.", "准备好开始了吗？": "Ready to start?", "用自己的电脑，完成一次有证据的模型训练。": "Train a model on your own computer, with evidence.", "让模型微调留在你的算力与数据边界里。": "Keep fine-tuning within your compute and data boundaries.", "法律与产品信息": "Legal and product information", "服务条款": "Terms", "隐私政策": "Privacy", "Cookie 政策": "Cookie Policy", "退款与取消": "Refunds & Cancellations", "数据权利": "Data Rights", "不出售或不分享": "Do Not Sell or Share", "AI 免责声明": "AI Disclaimer", "产品说明": "Product Supplement"
};

export function homeText(locale: "zh-CN" | "en", chinese: string) {
  return locale === "en" ? english[chinese] ?? chinese : chinese;
}

